package com.instantwin.slotmachine.view;

import java.math.BigDecimal;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Aggregated slot statistics for one user.")
public record SlotClientStatsView(
        @Schema(description = "ID of the user", example = "1") long userId,
        @Schema(description = "Number of slot games played by the user", example = "10") long totalGamesCount,
        @Schema(description = "Sum of all positive net game results", example = "100.00") BigDecimal totalWinnings,
        @Schema(description = "Absolute sum of all negative net game results", example = "60.00") BigDecimal totalLosses,
        @Schema(description = "User's total net result", example = "40.00") BigDecimal totalClientProfit,
        @Schema(description = "Sum of all bets placed by this user", example = "200.00") BigDecimal totalHouseTurnoverFromClient,
        @Schema(description = "House net result generated by this user", example = "-40.00") BigDecimal totalHouseProfitFromClient) {

    public long getUserId() {
        return userId;
    }

    public long getTotalGamesCount() {
        return totalGamesCount;
    }

    public BigDecimal getTotalWinnings() {
        return totalWinnings;
    }

    public BigDecimal getTotalLosses() {
        return totalLosses;
    }

    public BigDecimal getTotalClientProfit() {
        return totalClientProfit;
    }

    public BigDecimal getTotalHouseTurnoverFromClient() {
        return totalHouseTurnoverFromClient;
    }

    public BigDecimal getTotalHouseProfitFromClient() {
        return totalHouseProfitFromClient;
    }

}
