package com.instantwin.roulette.View;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.instantwin.roulette.contract.view.IUserStatsView;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Aggregated roulette statistics for one user.")
public class UserStatsView implements IUserStatsView {

    private final long client;
    private final long totalGamesCount;
    private final BigDecimal totalWinnings;
    private final BigDecimal totalLosses;
    private final BigDecimal totalClientProfit;
    private final BigDecimal totalHouseTurnoverFromClient;
    private final BigDecimal totalHouseProfitFromClient;

    private UserStatsView(long client, long totalGamesCount, BigDecimal totalWinnings,
                          BigDecimal totalLosses, BigDecimal totalClientProfit,
                          BigDecimal totalHouseTurnoverFromClient, BigDecimal totalHouseProfitFromClient) {
        this.client = client;
        this.totalGamesCount = totalGamesCount;
        this.totalWinnings = totalWinnings;
        this.totalLosses = totalLosses;
        this.totalClientProfit = totalClientProfit;
        this.totalHouseTurnoverFromClient = totalHouseTurnoverFromClient;
        this.totalHouseProfitFromClient = totalHouseProfitFromClient;
    }

    public static UserStatsView of(long client, long totalGamesCount, BigDecimal totalWinnings,
                                   BigDecimal totalLosses, BigDecimal totalClientProfit,
                                   BigDecimal totalHouseTurnoverFromClient, BigDecimal totalHouseProfitFromClient) {
        return new UserStatsView(client, totalGamesCount, totalWinnings, totalLosses,
                totalClientProfit, totalHouseTurnoverFromClient, totalHouseProfitFromClient);
    }

    @Override
    @JsonProperty("client")
    @Schema(description = "ID of the user", example = "1")
    public long getClient() { return client; }

    @Override
    @JsonProperty("totalGamesCount")
    @Schema(description = "Number of roulette games played by the user", example = "10")
    public long getTotalGamesCount() { return totalGamesCount; }

    @Override
    @JsonProperty("totalWinnings")
    @Schema(description = "Sum of positive net results from winning games", example = "100.00")
    public BigDecimal getTotalWinnings() { return totalWinnings; }

    @Override
    @JsonProperty("totalLosses")
    @Schema(description = "Sum of lost bet amounts", example = "60.00")
    public BigDecimal getTotalLosses() { return totalLosses; }

    @Override
    @JsonProperty("totalClientProfit")
    @Schema(description = "User's total net result", example = "40.00")
    public BigDecimal getTotalClientProfit() { return totalClientProfit; }

    @Override
    @JsonProperty("totalHouseTurnoverFromClient")
    @Schema(description = "Sum of all bets placed by this user", example = "200.00")
    public BigDecimal getTotalHouseTurnoverFromClient() { return totalHouseTurnoverFromClient; }

    @Override
    @JsonProperty("totalHouseProfitFromClient")
    @Schema(description = "House net result generated by this user", example = "-40.00")
    public BigDecimal getTotalHouseProfitFromClient() { return totalHouseProfitFromClient; }
}
